# Generated by Django 4.0.5 on 2022-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('pinned', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=200)),
                ('answers', models.JSONField(default=[])),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'unique_together': {('message_id', 'chat_id')},
            },
        ),
    ]
