# Generated by Django 4.0.5 on 2022-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
