# Generated by Django 4.0.5 on 2023-09-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_weeklypollanswer_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypoll',
            name='errors',
            field=models.IntegerField(default=0),
        ),
    ]
