# Generated by Django 4.0.5 on 2022-06-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_date', models.DateTimeField(auto_created=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('weekday', models.IntegerField(default=7)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
