# Generated by Django 4.0.5 on 2023-09-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_weeklypoll_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypoll',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
