# Generated by Django 4.0.5 on 2022-06-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_weeklypoll_alter_poll_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklypoll',
            name='poll_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklypoll',
            name='weekday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
