# Generated by Django 4.0.5 on 2022-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_weeklypoll_poll_date_alter_weeklypoll_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklypoll',
            name='poll_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
