# Generated by Django 4.0.5 on 2022-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_weeklypoll_poll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypoll',
            name='poll_id',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
