# Generated by Django 4.0.5 on 2022-06-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_weeklypoll_poll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklypoll',
            name='poll_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
