# Generated by Django 4.0.5 on 2022-06-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_weeklypoll_poll_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateTimeField(auto_created=True, verbose_name='date answered')),
                ('answer', models.IntegerField()),
                ('user', models.JSONField(default=dict)),
                ('wp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.weeklypoll')),
            ],
        ),
    ]
