# Generated by Django 4.0.5 on 2022-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_weeklypollanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklypollanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='weeklypollanswer',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklypollanswer',
            name='answer_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date answered'),
        ),
    ]
