# Generated by Django 4.0.5 on 2022-06-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_weeklypollanswer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypollanswer',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
