# Generated by Django 4.0.5 on 2022-06-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_weeklypollanswer_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklypollanswer',
            name='answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
