# Generated by Django 4.0.5 on 2022-06-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_weeklypollanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklypollanswer',
            name='answer',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
    ]
