# Generated by Django 4.0.5 on 2022-06-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_weeklypollanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypoll',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
