# Generated by Django 4.0.5 on 2022-06-13 21:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_weeklypoll_question_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypoll',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
