# Generated by Django 4.0.5 on 2022-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_weeklypoll_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklypoll',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
