# Generated by Django 4.0.5 on 2022-06-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_weeklypoll_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
