# Generated by Django 4.0.5 on 2022-06-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_usergame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playingtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='suggested_players',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(default='boardgame', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='bgg_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='groupgame',
            name='chat_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='chat_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='user_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
