# Generated by Django 4.0.5 on 2022-06-15 10:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_playingtime_game_suggested_players_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bgg_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='groupgame',
            name='owned_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='playscore',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
